### ISSUE TITLE
Cordova tarball downloads no longer work

### ISSUE THREAD

**Issue by Kestanous** [raix/Meteor-localforage-sqlite#1]
Just a heads up. 
```
While installing Cordova plugins:
   error: Meteor no longer supports installing Cordova plugins from arbitrary tarball URLs. You can either add a plugin from a Git URL with a SHA reference, or from a local path. (Attempting to install
   from https://github.com/litehelpers/Cordova-sqlite-storage/hash/e62f97ffb9daae8bd058c25e067943230e29049f.)
```

**Comment by raix** [comment]
ah, thanks man

**Comment by raix** [comment]
I'm sorry but its using the SHA hash?
I just fired up rc.7 and it build/downloaded cordova plugins fine?

**Comment by Kestanous** [comment]
That is there error it was giving me. I fixed it by using url#sha. I send you what I changed later tonight (EST). 

~Sivli Kestanous (cmtoups)

**Comment by raix** [comment]
just bumped using the actual version instead

**Comment by Kestanous** [comment]
Ah sorry, lost track of this. Resoled nicely with the updated version.
